[package]
name = "rodbus"
version = "0.1.0"
authors = ["Adam Crain <jadamcrain@automatak.com>", "Émile Grégoire <emile@automatak.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.0", features = ["tcp", "sync", "io-util", "rt-core", "macros"]}

[dev-dependencies]
assert_matches = "1.3.0"
tokio-test = "0.2.0"