[package]
name = "modbus-rs"
version = "0.1.0"
authors = ["Adam Crain <jadamcrain@automatak.com>", "Émile Grégoire <emile@automatak.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
tokio = "0.2.0-alpha.6"

[dev-dependencies]
assert_matches = "1.3.0"
